//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G_D_Residencia_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABITACIONE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HABITACIONE()
        {
            this.USUARIOS = new HashSet<USUARIO>();
        }
    
        public int id_habitacion { get; set; }
        public int id_edificio { get; set; }
        public int piso { get; set; }
        public string habitacion { get; set; }
        public string estado_habitacion { get; set; }
    
        public virtual EDIFICIO EDIFICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIOS { get; set; }
    }
}
