//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G_D_Residencia_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABITACIONE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HABITACIONE()
        {
            this.USUARIOS = new HashSet<USUARIO>();
        }
    
        public int id_habitacion { get; set; }
        public int id_edificio { get; set; }
        public int piso { get; set; }
        public string habitacion { get; set; }
        public string estado_habitacion { get; set; }
    
        public virtual EDIFICIO EDIFICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIOS { get; set; }
    }
}
