//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G_D_Residencia_V1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RESIDENT_SYSTEMEntities : DbContext
    {
        public RESIDENT_SYSTEMEntities()
            : base("name=RESIDENT_SYSTEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EDIFICIO> EDIFICIOS { get; set; }
        public virtual DbSet<HABITACIONE> HABITACIONES { get; set; }
        public virtual DbSet<REPORTES_AVERIAS> REPORTES_AVERIAS { get; set; }
        public virtual DbSet<SOLICITUD_ESTANCIA> SOLICITUD_ESTANCIA { get; set; }
        public virtual DbSet<SOLICITUD_SALIDA> SOLICITUD_SALIDA { get; set; }
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    }
}
