//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G_D_Residencia_V1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RESIDENT_SYSTEMEntities : DbContext
    {
        public RESIDENT_SYSTEMEntities()
            : base("name=RESIDENT_SYSTEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EDIFICIO> EDIFICIOS { get; set; }
        public virtual DbSet<HABITACIONE> HABITACIONES { get; set; }
        public virtual DbSet<REPORTES_AVERIAS> REPORTES_AVERIAS { get; set; }
        public virtual DbSet<SOLICITUD_ESTANCIA> SOLICITUD_ESTANCIA { get; set; }
        public virtual DbSet<SOLICITUD_SALIDA> SOLICITUD_SALIDA { get; set; }
        public virtual DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
    }
}
