//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G_D_Residencia_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTES_AVERIAS
    {
        public int id_averia { get; set; }
        public int id_usuario { get; set; }
        public string descripcion_averia { get; set; }
        public string status { get; set; }
        public System.DateTime fecha_solicitud { get; set; }
        public Nullable<System.DateTime> fecha_respuesta { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
