//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G_D_Residencia_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTES_AVERIAS
    {
        public int id_averia { get; set; }
        public int id_usuario { get; set; }
        public string descripcion_averia { get; set; }
        public string status { get; set; }
        public System.DateTime fecha_solicitud { get; set; }
        public Nullable<System.DateTime> fecha_respuesta { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
