//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G_D_Residencia_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.REPORTES_AVERIAS = new HashSet<REPORTES_AVERIAS>();
            this.SOLICITUD_ESTANCIA = new HashSet<SOLICITUD_ESTANCIA>();
            this.SOLICITUD_SALIDA = new HashSet<SOLICITUD_SALIDA>();
        }
    
        public int id_usuario { get; set; }
        public int id_tipo_usuario { get; set; }
        public Nullable<int> id_habitacion { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string matricula { get; set; }
        public string cedula { get; set; }
        public string telefono { get; set; }
        public string estado_usuario { get; set; }
        public System.DateTime fecha_nac { get; set; }
        public string sexo { get; set; }
        public string direccion { get; set; }
    
        public virtual HABITACIONE HABITACIONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORTES_AVERIAS> REPORTES_AVERIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD_ESTANCIA> SOLICITUD_ESTANCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD_SALIDA> SOLICITUD_SALIDA { get; set; }
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
    }
}
